export default [
  {
    name: 'hello-world-shiny-star-f6bf',
    requests: 124,
    errors: 1,
    lastModifiedTime: '2 hours',
    medianCPUTime: '0.3ms',
    customDomains: 0,
    routes: 1,
    cronTriggers: 0,
    emailTriggers: 0,
    connectedWorkflows: 0,
  },
  {
    name: 'image-compression-daisy-deer-a4vd',
    requests: 482,
    errors: 0,
    lastModifiedTime: '1 hour',
    medianCPUTime: '0.6ms',
    customDomains: 0,
    routes: 1,
    cronTriggers: 0,
    emailTriggers: 0,
    connectedWorkflows: 0,
  },
  {
    name: 'weather-tracking-funny-ferret-h8sd',
    requests: 17,
    errors: 0,
    lastModifiedTime: '50 minutes',
    medianCPUTime: '0.1ms',
    customDomains: 0,
    routes: 1,
    cronTriggers: 0,
    emailTriggers: 0,
    connectedWorkflows: 0,
  },
]
